# Расширение конфигурации Ruff

# Путь к исходникам, которые нужно проверять
src = ["price_monitoring", "common", "proxy_http", "tests"]

# Игнорируются файлы и директории
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".eggs",
    "*.egg",
    "coverage_html_report",
    "dm-trading-tools-master",
]

# Максимальная длина строки (должна соответствовать black)
line-length = 100

# Настройка isort
[lint.isort]
force-single-line = false
known-first-party = ["price_monitoring", "common", "proxy_http"]
force-sort-within-sections = true
combine-as-imports = true

# Настройка форматирования с помощью Ruff
[format]
quote-style = "double"  # Использование двойных кавычек
indent-style = "space"  # Использование пробелов для отступов
line-ending = "auto"    # Автоматическая установка окончаний строк

[lint]
# Включенные правила
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "A",    # flake8-builtins
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
    "PL",   # pylint
    "RUF",  # ruff-specific rules
    "D",    # pydocstyle
    "S",    # flake8-bandit
    "BLE",  # blind-except
    "FBT",  # boolean-trap
    "T20",  # print statements
]
# Игнорируемые правила
ignore = [
    "E501",    # Игнорируем ошибку длинных строк (будем использовать black для форматирования)
    "PLR0913",  # Слишком много аргументов функции (решим это в дальнейшем рефакторинге)
    "D203",    # Конфликт с D211
    "D213",    # Конфликт с D212
]

# Специальные настройки для тестов
[lint.per-file-ignores]
"tests/*" = [
    "S101",   # Использование assert в тестах
    "S301",   # pickle в тестах
    "S311",   # На генераторы псевдослучайных чисел в тестах
    "PLR2004", # Магические числа в тестах
    "D",      # Документация не так важна в тестах
    "ARG001", # Неиспользуемые аргументы в фикстурах
    "PLR0915", # Слишком много операторов в тестах
]
"conftest.py" = [
    "D",      # Документация не требуется в conftest.py
    "ARG001", # Неиспользуемые аргументы в фикстурах
]

# Настройки docstring
[lint.pydocstyle]
convention = "google"  # Используем Google стиль для документации
