name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.4.2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
        
    - name: Run black
      run: poetry run black --check --line-length=100 .
      
    - name: Run ruff
      run: poetry run ruff check .
      
    - name: Run pylint
      run: |
        poetry run pylint --max-line-length=100 price_monitoring/ bot_handlers/ common/ config/ monitoring/ tests/
      
    - name: Run mypy
      run: poetry run mypy
